#!/bin/bash
# Wrapper to run the Python Orchestrator with Mock Environment

# Ensure we are running from the project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_ROOT" || exit 1

# Generate Mock Test Config
echo "Generating mock test_config.env..."
WG_CONF_B64=$(base64 -w 0 "$SCRIPT_DIR/dummy_wg.conf")

cat > "$SCRIPT_DIR/test_config.env" <<EOF
# Mock Test Configuration generated by manual_verification.sh

# Network Configuration
export LAN_IP="127.0.0.1"
export PUBLIC_IP="127.0.0.1"

# Credentials
export DOCKER_USER="username"
export DOCKER_TOKEN="your_token_here"
export ADMIN_PASS_RAW="password"
export VPN_PASS_RAW="password"
export HUB_API_KEY="password"
export RIMGO_IMGUR_CLIENT_ID="546c25a59c58ad7"
export ODIDO_API_KEY="mock_key"
export ODIDO_USER_ID="mock_user"
export ODIDO_TOKEN="mock_token"
export WG_HASH_COMPOSE="mock_hash"
export PORTAINER_HASH_COMPOSE="mock_hash"
export SEARXNG_SECRET="mock_secret"
export IV_COMPANION="mock_companion"
export IV_HMAC="mock_hmac"
export IMMICH_DB_PASSWORD="mock_db_pass"
export VERT_SECRET="mock_secret"
export COBALT_SECRET="mock_secret"

# A/B System
export SLOT="a"
export APP_NAME="privacy-hub-test"

# WireGuard Configuration
export WG_CONF_B64="${WG_CONF_B64}"

# Feature Flags
export AUTO_CONFIRM="true"
export MOCK_VERIFICATION="true"
EOF

echo "Mock environment setup complete."

# Run Orchestrator
python3 "$SCRIPT_DIR/orchestrator.py"
